// backend/prisma/seed.ts
import { PrismaClient } from '@prisma/client';
import { Role } from '../src/types/enums';
import bcrypt from 'bcryptjs';
import dotenv from 'dotenv';

dotenv.config(); // Lade .env Variablen für das Seed-Skript

const prisma = new PrismaClient();

async function main() {
    console.log('Start seeding ...');

    const adminEmail = process.env.INITIAL_ADMIN_EMAIL || 'admin@example.com';
    const adminPassword = process.env.INITIAL_ADMIN_PASSWORD || 'changeme'; // Hole aus .env
    const adminName = process.env.INITIAL_ADMIN_NAME || 'Admin User';
    const adminUniHandle = process.env.INITIAL_ADMIN_UNIHANDLE || 'HS-Admin';

    if (adminPassword === 'changeme' || adminPassword.length < 8) {
        console.warn(
            'WARNING: Initial admin password is weak or default. Please set a strong INITIAL_ADMIN_PASSWORD in your .env file.',
        );
    }
    const hashedPassword = await bcrypt.hash(adminPassword, 10);

    // ...existing code...
    const adminUser = await prisma.user.upsert({
        where: { email: adminEmail },
        update: {
            // Optional: Update existing admin if needed
            password: hashedPassword, // Update password if it changed
            role: Role.ADMIN,
        },
        create: {
            email: adminEmail,
            name: adminName,
            password: hashedPassword,
            role: Role.ADMIN,
            uniHandle: adminUniHandle,
        },
    });
    console.log(`Created/updated admin user: ${adminUser.email}`);

    const questionsData = [
        {
            text: 'Welches ist das am häufigsten vorkommende Treibhausgas in der Erdatmosphäre, das maßgeblich zur globalen Erwärmung beiträgt?',
            optionA: 'Methan (CH4)',
            optionB: 'Lachgas (N2O)',
            optionC: 'Kohlendioxid (CO2)',
            optionD: 'Fluorierte Gase (F-Gase)',
            correctOption: 'C',
            category: 'Planetary Health',
            source: 'https://www.c2es.org/content/main-greenhouse-gases/',
            authorId: adminUser.id,
        },
        {
            text: 'Welches Treibhausgas hat das höchste globale Erwärmungspotenzial (GWP) über einen Zeitraum von 100 Jahren?',
            optionA: 'Kohlendioxid (CO2)',
            optionB: 'Methan (CH4)',
            optionC: 'Lachgas (N2O)',
            optionD: 'Schwefelhexafluorid (SF6)',
            correctOption: 'D',
            category: 'Planetary Health',
            source: 'https://ifeaa.com/sulfur-hexafluoride-sf6-the-most-potent-greenhouse-gas/',
            authorId: adminUser.id,
        },
        {
            text: 'Was misst die Keeling-Kurve?',
            optionA: 'Die Dicke der Ozonschicht',
            optionB: 'Die Konzentration von Kohlendioxid (CO2) in der Atmosphäre',
            optionC: 'Den durchschnittlichen globalen Meeresspiegelanstieg',
            optionD: 'Die jährliche globale Durchschnittstemperatur',
            correctOption: 'B',
            category: 'Planetary Health',
            source: 'https://keelingcurve.ucsd.edu/',
            authorId: adminUser.id,
        },
        {
            text: 'Was ist die Hauptursache für die Versauerung der Ozeane?',
            optionA: 'Ölverschmutzung durch Tankerunfälle',
            optionB: 'Einleitung von Industrieabwässern',
            optionC: 'Aufnahme von Kohlendioxid (CO2) aus der Atmosphäre',
            optionD: 'Plastikmüll in den Meeren',
            correctOption: 'C',
            category: 'Planetary Health',
            source: 'https://www.noaa.gov/education/resource-collections/ocean-coasts/ocean-acidification',
            authorId: adminUser.id,
        },
        {
            text: 'Welche zwei Hauptfaktoren tragen maßgeblich zum globalen Meeresspiegelanstieg im Zuge des Klimawandels bei?',
            optionA: 'Erhöhte Niederschlagsmengen und Flussmündungen',
            optionB: 'Schmelzen von Gletschern und Eisschilden sowie die thermische Ausdehnung des Meerwassers',
            optionC: 'Vulkanausbrüche unter Wasser und Erdbeben',
            optionD: 'Abholzung von Küstenwäldern und Bodenerosion',
            correctOption: 'B',
            category: 'Planetary Health',
            source: 'https://www.climate.gov/news-features/understanding-climate/climate-change-global-sea-level',
            authorId: adminUser.id,
        },
        {
            text: 'Welcher Sektor ist laut UN einer der Hauptverursacher von Treibhausgasemissionen?',
            optionA: 'Tourismus',
            optionB: 'Textilindustrie',
            optionC: 'Energieerzeugung',
            optionD: 'Unterhaltungselektronik',
            correctOption: 'C',
            category: 'Planetary Health',
            source: 'https://www.un.org/en/climatechange/what-is-climate-change',
            authorId: adminUser.id,
        },
        {
            text: 'Wie stark ist die Konzentration von CO2 in der Atmosphäre seit der vorindustriellen Zeit (vor 1750) bis 2020 laut der Europäischen Kommission gestiegen?',
            optionA: 'Um etwa 10%',
            optionB: 'Um etwa 25%',
            optionC: 'Um etwa 48%',
            optionD: 'Um etwa 75%',
            correctOption: 'C',
            category: 'Planetary Health',
            source: 'https://climate.ec.europa.eu/climate-change/causes-climate-change_en',
            authorId: adminUser.id,
        },
        {
            text: 'Welches Gas ist zwar mengenmäßig weniger stark in der Atmosphäre vertreten als CO2, aber pro Molekül deutlich wirksamer als Treibhausgas und hat eine kürzere atmosphärische Lebensdauer?',
            optionA: 'Sauerstoff (O2)',
            optionB: 'Stickstoff (N2)',
            optionC: 'Methan (CH4)',
            optionD: 'Argon (Ar)',
            correctOption: 'C',
            category: 'Planetary Health',
            source: 'https://climate.ec.europa.eu/climate-change/causes-climate-change_en',
            authorId: adminUser.id,
        },
        {
            text: 'Welchen Anteil an der globalen Erwärmung verursachen laut Wikipedia die CO2-Emissionen?',
            optionA: 'Etwa ein Viertel',
            optionB: 'Etwa die Hälfte',
            optionC: 'Etwa drei Viertel',
            optionD: 'Fast die gesamte Erwärmung',
            correctOption: 'C',
            category: 'Planetary Health',
            source: 'https://en.wikipedia.org/wiki/Greenhouse_gas',
            authorId: adminUser.id,
        },
        {
            text: 'Wo befindet sich das Mauna Loa Observatorium, an dem die Keeling-Kurve gemessen wird?',
            optionA: 'Antarktis',
            optionB: 'Hawaii, USA',
            optionC: 'Alpen, Schweiz',
            optionD: 'Himalaya, Nepal',
            correctOption: 'B',
            category: 'Planetary Health',
            source: 'https://en.wikipedia.org/wiki/Keeling_Curve',
            authorId: adminUser.id,
        },
        {
            text: 'Welchen Effekt hat die Ozeanversauerung auf Lebewesen mit Kalkschalen oder -skeletten (z.B. Korallen, Muscheln)?',
            optionA: 'Sie fördert ihr Wachstum.',
            optionB: 'Sie hat keinen nennenswerten Effekt.',
            optionC: 'Sie erschwert den Aufbau und Erhalt ihrer Schalen/Skelette.',
            optionD: 'Sie führt zu einer Verfärbung ihrer Schalen/Skelette.',
            correctOption: 'C',
            category: 'Planetary Health',
            source: 'https://www.noaa.gov/education/resource-collections/ocean-coasts/ocean-acidification',
            authorId: adminUser.id,
        },
        {
            text: 'Um wie viel ist der globale mittlere Meeresspiegel seit 1880 ungefähr gestiegen?',
            optionA: '5-10 Zentimeter',
            optionB: '10-15 Zentimeter',
            optionC: '21-24 Zentimeter',
            optionD: '30-35 Zentimeter',
            correctOption: 'C',
            category: 'Planetary Health',
            source: 'https://www.climate.gov/news-features/understanding-climate/climate-change-global-sea-level',
            authorId: adminUser.id,
        },
        {
            text: 'Welche menschliche Aktivität ist laut NASA die Hauptursache für die erhöhten Treibhausgaskonzentrationen?',
            optionA: 'Landwirtschaft',
            optionB: 'Industrielle Prozesse',
            optionC: 'Verbrennung fossiler Brennstoffe',
            optionD: 'Abfallentsorgung',
            correctOption: 'C',
            category: 'Planetary Health',
            source: 'https://science.nasa.gov/climate-change/causes/',
            authorId: adminUser.id,
        },
        {
            text: 'Welches Gas, das sowohl aus natürlichen Quellen als auch durch menschliche Aktivitäten (z.B. Viehzucht, Reisanbau, Deponien) freigesetzt wird, ist ein potentes Treibhausgas?',
            optionA: 'Neon (Ne)',
            optionB: 'Methan (CH4)',
            optionC: 'Helium (He)',
            optionD: 'Xenon (Xe)',
            correctOption: 'B',
            category: 'Planetary Health',
            source: 'https://science.nasa.gov/climate-change/causes/',
            authorId: adminUser.id,
        },
        {
            text: 'Was versteht man unter dem Begriff "Planetary Health"?',
            optionA: 'Die ausschließliche Gesundheit von Pflanzen und Tieren.',
            optionB: 'Die Gesundheit der menschlichen Zivilisation und der Zustand der natürlichen Systeme, von denen sie abhängt.',
            optionC: 'Die Erforschung außerirdischer Ökosysteme.',
            optionD: 'Ein neues Fitnessprogramm mit Fokus auf Outdoor-Aktivitäten.',
            correctOption: 'B',
            category: 'Planetary Health',
            source: 'https://www.thelancet.com/journals/lancet/article/PIIS0140-6736(15)61038-8/fulltext',
            authorId: adminUser.id,
        },
        {
            text: 'Wie viel Prozent des in die Atmosphäre freigesetzten CO2 wird etwa vom Ozean absorbiert?',
            optionA: 'Etwa 10%',
            optionB: 'Etwa 30%',
            optionC: 'Etwa 50%',
            optionD: 'Etwa 70%',
            correctOption: 'B',
            category: 'Planetary Health',
            source: 'https://www.noaa.gov/education/resource-collections/ocean-coasts/ocean-acidification',
            authorId: adminUser.id,
        },
        {
            text: 'Welche Auswirkung hat die thermische Ausdehnung des Meerwassers?',
            optionA: 'Es führt zu einer Abkühlung der Ozeane.',
            optionB: 'Es trägt zum Anstieg des Meeresspiegels bei.',
            optionC: 'Es erhöht den Salzgehalt der Ozeane.',
            optionD: 'Es verringert die Versauerung der Ozeane.',
            correctOption: 'B',
            category: 'Planetary Health',
            source: 'https://www.climate.gov/news-features/understanding-climate/climate-change-global-sea-level',
            authorId: adminUser.id,
        },
        {
            text: 'Welches internationale Abkommen zielt darauf ab, die globale Erwärmung auf deutlich unter 2°C, möglichst auf 1,5°C, im Vergleich zum vorindustriellen Niveau zu begrenzen?',
            optionA: 'Kyoto-Protokoll',
            optionB: 'Montreal-Protokoll',
            optionC: 'Pariser Abkommen',
            optionD: 'Rio-Konvention',
            correctOption: 'C',
            category: 'Planetary Health',
            source: 'https://climate.ec.europa.eu/climate-change/causes-climate-change_en',
            authorId: adminUser.id,
        },
        {
            text: 'Was ist ein "Tipping Point" (Kipppunkt) im Klimasystem?',
            optionA: 'Der Punkt, an dem die globale Durchschnittstemperatur zu sinken beginnt.',
            optionB: 'Ein Grenzwert, bei dessen Überschreitung sich das Klima abrupt und unumkehrbar verändert.',
            optionC: 'Der Zeitpunkt, an dem alle Länder klimaneutral werden.',
            optionD: 'Ein jährliches Treffen von Klimaexperten.',
            correctOption: 'B',
            category: 'Planetary Health',
            source: 'https://www.ipcc.ch/sr15/chapter/chapter-1/',
            authorId: adminUser.id,
        },
        {
            text: 'Welche Rolle spielt die Abholzung von Wäldern im Kontext des Klimawandels?',
            optionA: 'Sie hat keinen Einfluss auf das Klima.',
            optionB: 'Sie führt zur Freisetzung von gespeichertem CO2 und verringert die Fähigkeit der Erde, CO2 aufzunehmen.',
            optionC: 'Sie führt zu einer Erhöhung der globalen Sauerstoffproduktion.',
            optionD: 'Sie kühlt das lokale Klima durch mehr Schattenwurf.',
            correctOption: 'B',
            category: 'Planetary Health',
            source: 'https://www.un.org/en/climatechange/what-is-climate-change',
            authorId: adminUser.id,
        },
        {
            text: 'Welcher der folgenden menschlichen Ernährungsstile hat in der Regel den größten ökologischen Fußabdruck, insbesondere in Bezug auf Treibhausgasemissionen und Landnutzung?',
            optionA: 'Vegetarische Ernährung',
            optionB: 'Vegane Ernährung',
            optionC: 'Ernährung mit hohem Anteil an rotem Fleisch',
            optionD: 'Pescetarische Ernährung (Fisch, aber kein anderes Fleisch)',
            correctOption: 'C',
            category: 'Planetary Health',
            source: 'https://ourworldindata.org/food-choice-vs-eating-local',
            authorId: adminUser.id,
        },
        {
            text: 'Was versteht man unter "Korallenbleiche"?',
            optionA: 'Ein Prozess, bei dem Korallen ihre Farbe intensivieren.',
            optionB: 'Das Absterben von Korallen aufgrund von Meeresverschmutzung durch Chemikalien.',
            optionC: 'Das Ausstoßen der symbiotischen Algen durch Korallenpolypen, meist aufgrund erhöhter Wassertemperaturen, wodurch die Koralle weiß erscheint.',
            optionD: 'Eine Krankheit, die ausschließlich junge Korallen betrifft.',
            correctOption: 'C',
            category: 'Planetary Health',
            source: 'https://www.noaa.gov/education/resource-collections/ocean-coasts/coral-reef-ecosystems/coral-bleaching',
            authorId: adminUser.id,
        },
        {
            text: 'Welche Region der Erde erwärmt sich laut wissenschaftlichen Beobachtungen im Durchschnitt schneller als der globale Durchschnitt?',
            optionA: 'Die Tropen',
            optionB: 'Die gemäßigten Breiten der Südhalbkugel',
            optionC: 'Die Arktis',
            optionD: 'Die Wüstenregionen',
            correctOption: 'C',
            category: 'Planetary Health',
            source: 'https://www.arctic.noaa.gov/Report-Card/Report-Card-2023/ArtMID/8034/ArticleID/1035/Surface-Air-Temperature',
            authorId: adminUser.id,
        },
        {
            text: 'Was ist der Hauptzweck des Intergovernmental Panel on Climate Change (IPCC), oft als Weltklimarat bezeichnet?',
            optionA: 'Die Entwicklung neuer Technologien zur CO2-Reduktion.',
            optionB: 'Die Finanzierung von Klimaschutzprojekten in Entwicklungsländern.',
            optionC: 'Die regelmäßige Zusammenfassung und Bewertung des wissenschaftlichen Kenntnisstandes zum Klimawandel.',
            optionD: 'Die Organisation internationaler Klimaproteste.',
            correctOption: 'C',
            category: 'Planetary Health',
            source: 'https://www.ipcc.ch/about/',
            authorId: adminUser.id,
        },
        {
            text: 'Welche der folgenden erneuerbaren Energiequellen ist am stärksten von geografischen Gegebenheiten wie Sonneneinstrahlung oder Windmustern abhängig?',
            optionA: 'Geothermie',
            optionB: 'Biomasse',
            optionC: 'Solarenergie und Windenergie',
            optionD: 'Wasserkraft (große Staudämme)',
            correctOption: 'C',
            category: 'Planetary Health',
            source: 'https://www.energy.gov/eere/renewable-energy',
            authorId: adminUser.id,
        },
        {
            text: 'Was beschreibt der Begriff "Albedo"?',
            optionA: 'Die Menge an Wasser, die von einer Oberfläche verdunstet.',
            optionB: 'Das Rückstrahlvermögen einer Oberfläche für Sonnenlicht.',
            optionC: 'Die Fähigkeit eines Materials, Wärme zu speichern.',
            optionD: 'Die Geschwindigkeit, mit der sich ein Gletscher bewegt.',
            correctOption: 'B',
            category: 'Planetary Health',
            source: 'https://climate.nasa.gov/explore/ask-nasa-climate/3104/arctic-sea-ice-minimum-extent-is-a-grim-milestone/',
            authorId: adminUser.id,
        },
        {
            text: 'Welche Auswirkung hat schmelzendes Meereis (z.B. in der Arktis) direkt auf den globalen Meeresspiegel?',
            optionA: 'Es führt zu einem deutlichen Anstieg des Meeresspiegels.',
            optionB: 'Es führt zu einem leichten Absinken des Meeresspiegels.',
            optionC: 'Es hat keinen signifikanten direkten Einfluss auf den Meeresspiegel, da es bereits im Wasser schwimmt.',
            optionD: 'Es erhöht den Salzgehalt des umliegenden Wassers erheblich.',
            correctOption: 'C',
            category: 'Planetary Health',
            source: 'https://climate.nasa.gov/explore/ask-nasa-climate/2995/arctic-vs-antarctic-sea-ice-melt-whats-the-difference/',
            authorId: adminUser.id,
        },
        {
            text: 'Was ist eine häufige Folge von Dürreperioden, die durch den Klimawandel verschärft werden können, für die Landwirtschaft?',
            optionA: 'Erhöhte Ernteerträge durch mehr Sonnenstunden.',
            optionB: 'Verbesserte Bodenqualität durch Austrocknung.',
            optionC: 'Ernteausfälle und Wasserknappheit für Bewässerung.',
            optionD: 'Geringerer Schädlingsbefall.',
            correctOption: 'C',
            category: 'Planetary Health',
            source: 'https://www.un.org/en/climatechange/science/causes-effects-climate-change',
            authorId: adminUser.id,
        },
        {
            text: 'Welcher Planet in unserem Sonnensystem wird oft als Beispiel für einen extremen Treibhauseffekt genannt, der zu sehr hohen Oberflächentemperaturen führt?',
            optionA: 'Mars',
            optionB: 'Jupiter',
            optionC: 'Venus',
            optionD: 'Merkur',
            correctOption: 'C',
            category: 'Planetary Health',
            source: 'https://science.nasa.gov/solar-system/planets/venus/',
            authorId: adminUser.id,
        },
        {
            text: 'Was versteht man unter "Klimagerechtigkeit"?',
            optionA: 'Die Forderung, dass alle Länder exakt die gleiche Menge an CO2 emittieren dürfen.',
            optionB: 'Ein Konzept, das die ethischen und politischen Dimensionen des Klimawandels adressiert, insbesondere die ungleiche Verteilung von Ursachen und Folgen.',
            optionC: 'Ein juristisches Verfahren gegen Unternehmen, die das Klima schädigen.',
            optionD: 'Die wissenschaftliche Untersuchung, wie das Klima in der Vergangenheit war.',
            correctOption: 'B',
            category: 'Planetary Health',
            source: 'https://www.un.org/sustainabledevelopment/blog/2019/05/climate-justice/',
            authorId: adminUser.id,
        },
        {
            text: 'Welche Rolle spielen Mangrovenwälder für den Küstenschutz und das Klima?',
            optionA: 'Sie beschleunigen die Küstenerosion.',
            optionB: 'Sie dienen als Wellenbrecher, schützen vor Stürmen und speichern große Mengen Kohlenstoff.',
            optionC: 'Sie haben keinen nennenswerten Einfluss auf Küsten oder Klima.',
            optionD: 'Sie sind primär eine Quelle für Holz und tragen zur Entwaldung bei.',
            correctOption: 'B',
            category: 'Planetary Health',
            source: 'https://www.noaa.gov/education/resource-collections/ocean-coasts/mangrove-forests',
            authorId: adminUser.id,
        },
        {
            text: 'Was ist der Hauptunterschied zwischen Wetter und Klima?',
            optionA: 'Wetter beschreibt die Temperatur, Klima den Niederschlag.',
            optionB: 'Wetter ist der kurzfristige Zustand der Atmosphäre, Klima der langfristige Durchschnitt des Wetters.',
            optionC: 'Wetter wird von Menschen beeinflusst, Klima nicht.',
            optionD: 'Es gibt keinen Unterschied, die Begriffe sind synonym.',
            correctOption: 'B',
            category: 'Planetary Health',
            source: 'https://www.nasa.gov/mission_pages/noaa-n/climate/climate_weather.html',
            authorId: adminUser.id,
        },
        {
            text: 'Welche der folgenden Krankheiten wird mit der Ausbreitung von krankheitsübertragenden Insekten (z.B. Mücken) in neue Regionen infolge des Klimawandels in Verbindung gebracht?',
            optionA: 'Grippe',
            optionB: 'Tuberkulose',
            optionC: 'Dengue-Fieber',
            optionD: 'Masern',
            correctOption: 'C',
            category: 'Planetary Health',
            source: 'https://www.who.int/news-room/fact-sheets/detail/climate-change-and-health',
            authorId: adminUser.id,
        },
        {
            text: 'Was versteht man unter dem Begriff "Kohlenstoff-Fußabdruck"?',
            optionA: 'Die Gesamtmenge an Kohlenstoff, die in einem Produkt enthalten ist.',
            optionB: 'Die Gesamtmenge an Treibhausgasen, die direkt und indirekt durch eine Aktivität, eine Person oder ein Produkt verursacht wird, ausgedrückt in CO2-Äquivalenten.',
            optionC: 'Die Fläche an Wald, die benötigt wird, um den CO2-Ausstoß einer Person zu kompensieren.',
            optionD: 'Ein Maß für die Bodenqualität in kohlenstoffreichen Gebieten.',
            correctOption: 'B',
            category: 'Planetary Health',
            source: 'https://www.nature.org/en-us/get-involved/how-to-help/carbon-footprint-calculator/',
            authorId: adminUser.id,
        },
        {
            text: 'Welcher Ozean ist der größte und tiefste der Erde und spielt eine Schlüsselrolle bei der globalen Wärmeregulierung?',
            optionA: 'Atlantischer Ozean',
            optionB: 'Indischer Ozean',
            optionC: 'Pazifischer Ozean',
            optionD: 'Arktischer Ozean',
            correctOption: 'C',
            category: 'Planetary Health',
            source: 'https://www.noaa.gov/education/resource-collections/ocean-coasts/pacific-ocean',
            authorId: adminUser.id,
        },
        {
            text: 'Was ist ein "urbaner Hitzeinseleffekt"?',
            optionA: 'Eine plötzliche Hitzewelle, die nur Städte betrifft.',
            optionB: 'Das Phänomen, dass städtische Gebiete tendenziell wärmer sind als ihre ländliche Umgebung.',
            optionC: 'Eine spezielle Art von Klimaanlage für Großstädte.',
            optionD: 'Die Verlagerung von Hitze aus ländlichen Gebieten in Städte.',
            correctOption: 'B',
            category: 'Planetary Health',
            source: 'https://www.epa.gov/heatislands/learn-about-heat-islands',
            authorId: adminUser.id,
        },
        {
            text: 'Welche der folgenden Maßnahmen trägt NICHT direkt zur Reduzierung von Treibhausgasemissionen bei?',
            optionA: 'Ausbau erneuerbarer Energien',
            optionB: 'Erhöhung der Energieeffizienz',
            optionC: 'Aufforstung von Wäldern',
            optionD: 'Bau höherer Deiche zum Schutz vor Meeresspiegelanstieg',
            correctOption: 'D',
            category: 'Planetary Health',
            source: 'https://www.epa.gov/arc-x/climate-adaptation-and-mitigation',
            authorId: adminUser.id,
        },
        {
            text: 'Was ist die Hauptfunktion der Ozonschicht in der Stratosphäre?',
            optionA: 'Sie erzeugt das Wetter auf der Erde.',
            optionB: 'Sie absorbiert den größten Teil der schädlichen ultravioletten (UV) Strahlung der Sonne.',
            optionC: 'Sie hält die Wärme in der Atmosphäre zurück (Treibhauseffekt).',
            optionD: 'Sie ist die Quelle für den Sauerstoff, den wir atmen.',
            correctOption: 'B',
            category: 'Planetary Health',
            source: 'https://www.epa.gov/ozone-layer-protection/basic-ozone-layer-science',
            authorId: adminUser.id,
        },
        {
            text: 'Welcher Begriff beschreibt die Fähigkeit eines Ökosystems, Störungen zu widerstehen und sich davon zu erholen?',
            optionA: 'Produktivität',
            optionB: 'Biodiversität',
            optionC: 'Resilienz',
            optionD: 'Sukzession',
            correctOption: 'C',
            category: 'Planetary Health',
            source: 'https://www.stockholmresilience.org/research/research-news/2015-02-19-what-is-resilience.html',
            authorId: adminUser.id,
        },
        {
            text: 'Wie beeinflusst der Klimawandel tendenziell die Häufigkeit und Intensität von Extremwetterereignissen wie Hitzewellen, Starkniederschlägen und Dürren?',
            optionA: 'Er verringert ihre Häufigkeit und Intensität.',
            optionB: 'Er hat keinen Einfluss darauf.',
            optionC: 'Er erhöht tendenziell ihre Häufigkeit und Intensität.',
            optionD: 'Er führt nur zu mehr Hitzewellen, aber weniger Starkniederschlägen.',
            correctOption: 'C',
            category: 'Planetary Health',
            source: 'https://www.ipcc.ch/report/ar6/wg1/chapter/chapter-11/',
            authorId: adminUser.id,
        },
        {
            text: 'Was ist die Hauptgefahr beim Tauen von Permafrostböden in Bezug auf den Klimawandel?',
            optionA: 'Freisetzung großer Mengen an Süßwasser, was den Salzgehalt der Meere verändert.',
            optionB: 'Absenkung des Bodens und damit verbundene Schäden an der Infrastruktur.',
            optionC: 'Freisetzung von im Eis gefangenen alten Viren und Bakterien.',
            optionD: 'Freisetzung großer Mengen an Treibhausgasen (Methan und CO2) durch die Zersetzung organischen Materials.',
            correctOption: 'D',
            category: 'Planetary Health',
            source: 'https://www.ouranos.ca/en/program/impacts-of-thawing-permafrost/',
            authorId: adminUser.id,
        },
        {
            text: 'Welche der folgenden Aussagen beschreibt Biodiversität am besten?',
            optionA: 'Die Anzahl der Individuen einer bestimmten Tierart in einem Ökosystem.',
            optionB: 'Die Vielfalt des Lebens auf der Erde auf allen Ebenen, von Genen über Arten bis hin zu Ökosystemen.',
            optionC: 'Die Gesamtmasse aller lebenden Organismen in einem bestimmten Gebiet.',
            optionD: 'Die Geschwindigkeit, mit der neue Arten durch Evolution entstehen.',
            correctOption: 'B',
            category: 'Planetary Health',
            source: 'https://www.ifaw.org/journal/what-is-biodiversity-and-why-is-it-important',
            authorId: adminUser.id,
        },
        {
            text: 'Was ist laut "The Ocean Cleanup" eine Hauptquelle für Plastikmüll im Großen Pazifischen Müllstrudel (Great Pacific Garbage Patch)?',
            optionA: 'Abwässer aus Küstenstädten',
            optionB: 'Tourismus auf Kreuzfahrtschiffen',
            optionC: 'Fischereiaktivitäten auf See (z.B. verlorene Netze)',
            optionD: 'Industrieabfälle, die direkt ins Meer geleitet werden',
            correctOption: 'C',
            category: 'Planetary Health',
            source: 'https://theoceancleanup.com/plastic-pollution/',
            authorId: adminUser.id,
        },
        {
            text: 'Welcher Aspekt der "Fast Fashion"-Industrie trägt laut UN-Umweltprogramm maßgeblich zu ihrem hohen Wasserverbrauch und CO2-Fußabdruck bei?',
            optionA: 'Der Transport der fertigen Kleidung in die Geschäfte.',
            optionB: 'Die energieintensive Herstellung von synthetischen Fasern und die Färbung von Textilien.',
            optionC: 'Der Wasserverbrauch beim Waschen der Kleidung durch die Konsumenten.',
            optionD: 'Die Verpackung der Kleidungsstücke.',
            correctOption: 'B',
            category: 'Planetary Health',
            source: 'https://www.earth.org/fast-fashion-environmental-impact/',
            authorId: adminUser.id,
        },
        {
            text: 'Welche sind die beiden Haupttreibhausgase, die direkt aus landwirtschaftlichen Aktivitäten (ohne Landnutzungsänderungen) stammen?',
            optionA: 'Kohlendioxid (CO2) und Ozon (O3)',
            optionB: 'Methan (CH4) und Lachgas (N2O)',
            optionC: 'Schwefeldioxid (SO2) und Stickoxide (NOx)',
            optionD: 'Fluorierte Gase (F-Gase) und Wasserdampf (H2O)',
            correctOption: 'B',
            category: 'Planetary Health',
            source: 'https://en.wikipedia.org/wiki/Greenhouse_gas_emissions_from_agriculture',
            authorId: adminUser.id,
        },
        {
            text: 'Was sind Mikroplastikpartikel per Definition?',
            optionA: 'Plastikpartikel, die nur unter dem Elektronenmikroskop sichtbar sind.',
            optionB: 'Plastikpartikel, die kleiner als 5 Millimeter sind.',
            optionC: 'Plastikpartikel, die ausschließlich aus Polyethylen bestehen.',
            optionD: 'Plastikpartikel, die biologisch abbaubar sind.',
            correctOption: 'B',
            category: 'Planetary Health',
            source: 'https://oceanservice.noaa.gov/facts/microplastics.html',
            authorId: adminUser.id,
        },
        {
            text: 'Wie trägt die Entwaldung hauptsächlich zur globalen Erwärmung bei?',
            optionA: 'Durch die Verringerung der Sauerstoffproduktion.',
            optionB: 'Durch die Freisetzung von in Bäumen gespeichertem Kohlenstoff und die Reduzierung der Kohlenstoffaufnahme.',
            optionC: 'Durch die Erhöhung der Albedo (Rückstrahlvermögen) der Erdoberfläche.',
            optionD: 'Durch die Störung lokaler Windmuster.',
            correctOption: 'B',
            category: 'Planetary Health',
            source: 'https://www.climateimpactpartners.com/insights/the-effects-of-deforestation/',
            authorId: adminUser.id,
        },
        {
            text: 'Was ist eine Hauptursache für physische Wasserknappheit?',
            optionA: 'Mangelnde Investitionen in Wasserinfrastruktur.',
            optionB: 'Ungleiche Verteilung des Wassers aufgrund politischer Konflikte.',
            optionC: 'Wenn die natürlichen Wasserressourcen nicht ausreichen, um den gesamten Bedarf (einschließlich ökologischer Bedürfnisse) zu decken.',
            optionD: 'Ineffiziente Wassernutzung in der Landwirtschaft.',
            correctOption: 'C',
            category: 'Planetary Health',
            source: 'https://en.wikipedia.org/wiki/Water_scarcity',
            authorId: adminUser.id,
        },
        {
            text: 'Welche der folgenden Gesundheitsauswirkungen wird laut WHO am stärksten mit der Exposition gegenüber Luftverschmutzung in Verbindung gebracht?',
            optionA: 'Hautausschläge und Allergien',
            optionB: 'Verdauungsstörungen',
            optionC: 'Herz-Kreislauf-Erkrankungen (z.B. Schlaganfall, ischämische Herzkrankheit) und Atemwegserkrankungen',
            optionD: 'Gelenkschmerzen und Arthritis',
            correctOption: 'C',
            category: 'Planetary Health',
            source: 'https://www.who.int/teams/environment-climate-change-and-health/air-quality-energy-and-health/health-impacts/exposure-air-pollution',
            authorId: adminUser.id,
        },
        {
            text: 'Was versteht man unter Ozean-Deoxygenierung?',
            optionA: 'Die Zunahme des Sauerstoffgehalts in den Ozeanen durch vermehrtes Algenwachstum.',
            optionB: 'Die Abnahme des Sauerstoffgehalts in den Ozeanen, oft verursacht durch Erwärmung und Nährstoffeinträge.',
            optionC: 'Ein Prozess zur Reinigung von Meerwasser von Schadstoffen.',
            optionD: 'Die Anreicherung der Ozeane mit Sauerstoff durch technische Maßnahmen.',
            correctOption: 'B',
            category: 'Planetary Health',
            source: 'https://scripps.ucsd.edu/news/faq-ocean-deoxygenation',
            authorId: adminUser.id,
        },
        {
            text: 'Was ist das Hauptziel des Sustainable Development Goal 13 (SDG 13) der Vereinten Nationen?',
            optionA: 'Die Förderung erneuerbarer Energien weltweit.',
            optionB: 'Der Schutz der marinen Biodiversität.',
            optionC: 'Dringende Maßnahmen zur Bekämpfung des Klimawandels und seiner Auswirkungen zu ergreifen.',
            optionD: 'Die Sicherstellung einer nachhaltigen Wasserwirtschaft für alle.',
            correctOption: 'C',
            category: 'Planetary Health',
            source: 'https://en.wikipedia.org/wiki/Sustainable_Development_Goal_13',
            authorId: adminUser.id,
        },
        {
            text: 'Wie trägt Lebensmittelverschwendung zur globalen Erwärmung bei?',
            optionA: 'Hauptsächlich durch den Energieverbrauch bei der Kühlung von Lebensmitteln.',
            optionB: 'Durch die Produktion von Methan, einem potenten Treibhausgas, wenn Lebensmittel auf Mülldeponien verrotten.',
            optionC: 'Durch den erhöhten Wasserverbrauch für die Produktion von Lebensmitteln, die dann weggeworfen werden.',
            optionD: 'Durch den Verpackungsmüll, der bei Lebensmitteln anfällt.',
            correctOption: 'B',
            category: 'Planetary Health',
            source: 'https://www.worldwildlife.org/stories/fight-climate-change-by-preventing-food-waste',
            authorId: adminUser.id,
        },
        {
            text: 'Was ist das Kernprinzip einer Kreislaufwirtschaft (Circular Economy)?',
            optionA: 'Maximierung der Produktion von Gütern zu niedrigsten Kosten.',
            optionB: 'Produkte und Materialien so lange wie möglich in Gebrauch zu halten, Abfall zu minimieren und Ressourcen wiederzuverwenden.',
            optionC: 'Fokus auf den Export von recycelten Materialien in andere Länder.',
            optionD: 'Förderung des einmaligen Gebrauchs von Produkten, um die Nachfrage anzukurbeln.',
            correctOption: 'B',
            category: 'Planetary Health',
            source: 'https://www.europarl.europa.eu/news/en/headlines/economy/20151201STO05603/circular-economy-definition-importance-and-benefits',
            authorId: adminUser.id,
        },
        {
            text: 'Welche wichtige Rolle spielen Feuchtgebiete im Kohlenstoffkreislauf?',
            optionA: 'Sie sind Hauptquellen für die Freisetzung von Kohlendioxid durch schnelle Zersetzung.',
            optionB: 'Sie speichern große Mengen Kohlenstoff im Boden und in der Vegetation und entziehen ihn so der Atmosphäre.',
            optionC: 'Sie haben kaum Einfluss auf den globalen Kohlenstoffkreislauf.',
            optionD: 'Sie wandeln Kohlenstoffdioxid direkt in Sauerstoff um, ohne ihn zu speichern.',
            correctOption: 'B',
            category: 'Planetary Health',
            source: 'https://bwsr.state.mn.us/carbon-sequestration-wetlands',
            authorId: adminUser.id,
        },
        {
            text: 'Was beschreibt das "One Health"-Konzept?',
            optionA: 'Ein Ansatz, der sich ausschließlich auf die menschliche Gesundheit konzentriert.',
            optionB: 'Die Idee, dass die Gesundheit von Menschen, Tieren und der Umwelt eng miteinander verbunden sind und einen integrierten Ansatz erfordern.',
            optionC: 'Eine neue Versicherungspolice, die Tierarztkosten und menschliche Gesundheitskosten abdeckt.',
            optionD: 'Ein Programm zur Förderung von Fitness und Wohlbefinden in Entwicklungsländern.',
            correctOption: 'B',
            category: 'Planetary Health',
            source: 'https://www.cdc.gov/onehealth/about/index.html',
            authorId: adminUser.id,
        },
        {
            text: 'Was ist eine typische ökologische Auswirkung von invasiven Arten in einem neuen Ökosystem?',
            optionA: 'Sie erhöhen immer die lokale Artenvielfalt.',
            optionB: 'Sie konkurrieren mit einheimischen Arten um Ressourcen und können deren Populationen reduzieren.',
            optionC: 'Sie dienen ausschließlich als neue Nahrungsquelle für einheimische Raubtiere.',
            optionD: 'Sie passen sich immer perfekt an und füllen eine unbesetzte ökologische Nische.',
            correctOption: 'B',
            category: 'Planetary Health',
            source: 'https://ckiss.ca/about/impacts-of-invasive-species/',
            authorId: adminUser.id,
        },
        {
            text: 'Welches ist ein Hauptgesundheitsrisiko, das mit Hitzewellen in Verbindung gebracht wird?',
            optionA: 'Erhöhtes Risiko für Erfrierungen.',
            optionB: 'Verschlimmerung von Gelenkerkrankungen.',
            optionC: 'Hitzschlag und Verschlimmerung von Herz-Kreislauf-Erkrankungen.',
            optionD: 'Zunahme von Magen-Darm-Infektionen.',
            correctOption: 'C',
            category: 'Planetary Health',
            source: 'https://www.who.int/news-room/fact-sheets/detail/heat-and-health',
            authorId: adminUser.id,
        },
        {
            text: 'Wie wirkt sich Lichtverschmutzung typischerweise auf nachtaktive Wildtiere aus?',
            optionA: 'Sie verbessert ihre Orientierungsfähigkeit.',
            optionB: 'Sie stört ihre natürlichen Verhaltensweisen wie Nahrungssuche, Fortpflanzung und Schutz vor Raubtieren.',
            optionC: 'Sie hat keinen nennenswerten Einfluss auf nachtaktive Tiere.',
            optionD: 'Sie lockt mehr Beutetiere an und erleichtert ihnen die Jagd.',
            correctOption: 'B',
            category: 'Planetary Health',
            source: 'https://darksky.org/light-pollution/wildlife/',
            authorId: adminUser.id,
        },
        {
            text: 'Was ist eine der Hauptfolgen von Bodendegradation für die Landwirtschaft?',
            optionA: 'Erhöhung der Bodenfruchtbarkeit durch Nährstoffanreicherung.',
            optionB: 'Verringerung der Ernteerträge und der Nahrungsmittelproduktion.',
            optionC: 'Bessere Wasserspeicherung im Boden.',
            optionD: 'Geringerer Bedarf an Düngemitteln.',
            correctOption: 'B',
            category: 'Planetary Health',
            source: 'https://eos.com/blog/soil-degradation/',
            authorId: adminUser.id,
        },
        {
            text: 'Was sind "Nationally Determined Contributions" (NDCs) im Rahmen des Pariser Klimaabkommens?',
            optionA: 'Finanzielle Beiträge von Industrieländern an Entwicklungsländer für Klimaschutz.',
            optionB: 'Von jedem Land selbst festgelegte nationale Klimaschutzziele zur Reduktion von Emissionen und zur Anpassung an den Klimawandel.',
            optionC: 'International verbindliche Emissionsgrenzwerte für jeden Sektor.',
            optionD: 'Berichte über die wissenschaftlichen Erkenntnisse zum Klimawandel.',
            correctOption: 'B',
            category: 'Planetary Health',
            source: 'https://unfccc.int/process-and-meetings/the-paris-agreement/nationally-determined-contributions-ndcs',
            authorId: adminUser.id,
        },
        {
            text: 'Welche der folgenden Energiequellen gilt als nicht-erneuerbar und trägt maßgeblich zur Emission von Treibhausgasen bei?',
            optionA: 'Solarenergie',
            optionB: 'Windenergie',
            optionC: 'Kohle',
            optionD: 'Geothermie',
            correctOption: 'C',
            category: 'Planetary Health',
            source: 'https://www.nationalgeographic.org/encyclopedia/nonrenewable-resources/',
            authorId: adminUser.id,
        },
        {
            text: 'Was versteht man unter "virtuellem Wasser"?',
            optionA: 'Wasser, das durch Verdunstung in die Atmosphäre gelangt.',
            optionB: 'Die Menge an Wasser, die zur Herstellung eines Produkts (z.B. Lebensmittel, Kleidung) über dessen gesamte Wertschöpfungskette hinweg verbraucht wird.',
            optionC: 'Aufbereitetes Abwasser, das wieder als Trinkwasser genutzt wird.',
            optionD: 'Wasser, das in unterirdischen Aquiferen gespeichert ist.',
            correctOption: 'B',
            category: 'Planetary Health',
            source: 'https://www.watercalculator.org/water-footprint/virtual-water/',
            authorId: adminUser.id,
        },
        {
            text: 'Welche Rolle spielen Phytoplankton-Organismen in den Ozeanen für das globale Klima?',
            optionA: 'Sie sind Hauptverursacher der Ozeanversauerung.',
            optionB: 'Sie produzieren einen erheblichen Teil des weltweiten Sauerstoffs und binden Kohlendioxid durch Photosynthese.',
            optionC: 'Sie tragen zur Erwärmung der oberen Wasserschichten bei.',
            optionD: 'Sie sind primär für die Zersetzung von organischem Material in der Tiefsee verantwortlich.',
            correctOption: 'B',
            category: 'Planetary Health',
            source: 'https://earthobservatory.nasa.gov/features/Phytoplankton',
            authorId: adminUser.id,
        },
        {
            text: 'Was ist ein Hauptproblem bei der Entsorgung von Elektroschrott (E-Waste), insbesondere in Ländern mit geringen Umweltstandards?',
            optionA: 'Die Geräte sind zu sperrig für herkömmliche Mülldeponien.',
            optionB: 'Die Freisetzung von wertvollen Metallen, die dann verloren gehen.',
            optionC: 'Die Freisetzung von giftigen Substanzen wie Blei, Quecksilber und Cadmium in die Umwelt.',
            optionD: 'Der hohe Energieaufwand für das Recycling der Kunststoffgehäuse.',
            correctOption: 'C',
            category: 'Planetary Health',
            source: 'https://www.who.int/news-room/fact-sheets/detail/electronic-waste-(e-waste)',
            authorId: adminUser.id,
        },
        {
            text: 'Welcher Sektor ist laut FAO (Ernährungs- und Landwirtschaftsorganisation der Vereinten Nationen) einer der größten Nutzer von Süßwasserressourcen weltweit?',
            optionA: 'Industrie',
            optionB: 'Haushalte',
            optionC: 'Landwirtschaft (insbesondere für Bewässerung)',
            optionD: 'Energieerzeugung (Kühlung von Kraftwerken)',
            correctOption: 'C',
            category: 'Planetary Health',
            source: 'https://www.fao.org/aquastat/en/overview/methodology/water-use',
            authorId: adminUser.id,
        },
        {
            text: 'Was ist der primäre Mechanismus, durch den der Verlust der Artenvielfalt die Stabilität von Ökosystemen beeinträchtigen kann?',
            optionA: 'Es führt zu einer Zunahme von Raubtieren.',
            optionB: 'Es verringert die genetische Vielfalt und damit die Anpassungsfähigkeit an Umweltveränderungen und reduziert die Redundanz wichtiger ökologischer Funktionen.',
            optionC: 'Es erhöht die Konkurrenz zwischen den verbleibenden Arten.',
            optionD: 'Es führt immer zu einer Zunahme der Biomasseproduktion.',
            correctOption: 'B',
            category: 'Planetary Health',
            source: 'https://www.nature.com/scitable/knowledge/library/biodiversity-and-ecosystem-stability-17059965/',
            authorId: adminUser.id,
        },
        {
            text: 'Welche Auswirkung hat die Zerstörung von Korallenriffen auf Küstengemeinden?',
            optionA: 'Erhöhter Tourismus durch leichteren Zugang zu Stränden.',
            optionB: 'Verbesserte Fischfangquoten, da Fische sich neue Lebensräume suchen.',
            optionC: 'Verlust des natürlichen Küstenschutzes vor Stürmen und Wellen sowie Einbußen bei Fischerei und Tourismus.',
            optionD: 'Keine signifikanten Auswirkungen, da Korallenriffe meist weit vor der Küste liegen.',
            correctOption: 'C',
            category: 'Planetary Health',
            source: 'https://www.icriforum.org/about-coral-reefs/why-are-coral-reefs-important/',
            authorId: adminUser.id,
        },
        {
            text: 'Was ist ein "ökologischer Fußabdruck"?',
            optionA: 'Die Fläche, die eine Person zum Gehen benötigt.',
            optionB: 'Ein Maß für die menschliche Nachfrage nach den natürlichen Ressourcen der Erde im Vergleich zur Regenerationsfähigkeit der Erde.',
            optionC: 'Die Menge an CO2, die eine Person pro Jahr ausstößt.',
            optionD: 'Die Anzahl der Tierarten, die durch menschliche Aktivitäten gefährdet sind.',
            correctOption: 'B',
            category: 'Planetary Health',
            source: 'https://www.footprintnetwork.org/our-work/ecological-footprint/',
            authorId: adminUser.id,
        },
        {
            text: 'Welche der folgenden Praktiken gilt als eine Methode der nachhaltigen Landwirtschaft?',
            optionA: 'Monokulturen über große Flächen.',
            optionB: 'Intensiver Einsatz von synthetischen Pestiziden und Düngemitteln.',
            optionC: 'Fruchtfolge und Anbau von Zwischenfrüchten zur Verbesserung der Bodengesundheit.',
            optionD: 'Vollständige Entfernung aller Ernterückstände vom Feld.',
            correctOption: 'C',
            category: 'Planetary Health',
            source: 'https://www.ucsusa.org/resources/what-sustainable-agriculture',
            authorId: adminUser.id,
        },
        {
            text: 'Was ist die Hauptursache für die Bildung von "Todeszonen" (hypoxische Zonen) in Küstengewässern?',
            optionA: 'Überfischung, die das ökologische Gleichgewicht stört.',
            optionB: 'Einleitung von heißem Kühlwasser aus Industrieanlagen.',
            optionC: 'Übermäßiger Nährstoffeintrag (z.B. aus Düngemitteln), der zu Algenblüten und anschließendem Sauerstoffmangel durch Zersetzung führt.',
            optionD: 'Ölverschmutzungen, die die Wasseroberfläche versiegeln.',
            correctOption: 'C',
            category: 'Planetary Health',
            source: 'https://oceanservice.noaa.gov/facts/deadzone.html',
            authorId: adminUser.id,
        },
        {
            text: 'Welche Rolle spielt die planetare Belastungsgrenze (Planetary Boundary) "Klimawandel" im Konzept der planetaren Grenzen?',
            optionA: 'Sie ist die einzige Grenze, die bereits überschritten wurde.',
            optionB: 'Sie ist eine von mehreren kritischen Grenzen, deren Überschreitung die Stabilität des Erdsystems gefährden kann.',
            optionC: 'Sie hat den geringsten Einfluss auf die menschliche Gesundheit.',
            optionD: 'Sie kann durch technologische Innovationen leicht wieder in einen sicheren Bereich gebracht werden.',
            correctOption: 'B',
            category: 'Planetary Health',
            source: 'https://www.stockholmresilience.org/research/planetary-boundaries/the-nine-planetary-boundaries.html',
            authorId: adminUser.id,
        },
        {
            text: 'Wie kann der Konsum von lokal und saisonal produzierten Lebensmitteln zur Reduzierung des ökologischen Fußabdrucks beitragen?',
            optionA: 'Hauptsächlich durch die Vermeidung von Verpackungsmüll.',
            optionB: 'Durch die Reduzierung von Transportemissionen und potenziell geringeren Energieaufwand für Lagerung (z.B. in Kühlhäusern).',
            optionC: 'Weil lokale Produkte immer biologisch angebaut werden.',
            optionD: 'Weil saisonale Produkte weniger Wasser für den Anbau benötigen.',
            correctOption: 'B',
            category: 'Planetary Health',
            source: 'https://www.earthday.org/eat-local-seasonal-food/',
            authorId: adminUser.id,
        },
        {
            text: 'Was ist ein wesentlicher Nachteil der Energiegewinnung aus fossilen Brennstoffen im Vergleich zu den meisten erneuerbaren Energien?',
            optionA: 'Höhere Betriebskosten der Kraftwerke.',
            optionB: 'Geringere Energiedichte.',
            optionC: 'Freisetzung von Treibhausgasen und Luftschadstoffen.',
            optionD: 'Stärkere Abhängigkeit von Wetterbedingungen.',
            correctOption: 'C',
            category: 'Planetary Health',
            source: 'https://www.eia.gov/energyexplained/nonrenewable-sources/',
            authorId: adminUser.id,
        },
        {
            text: 'Was versteht man unter "Wasserstress"?',
            optionA: 'Wenn die Nachfrage nach Wasser die verfügbare Menge in einem bestimmten Zeitraum übersteigt oder wenn eine schlechte Qualität die Nutzung einschränkt.',
            optionB: 'Der Druck, den Wasser auf die Wände von Behältern ausübt.',
            optionC: 'Die Anstrengung, die erforderlich ist, um Wasser aus tiefen Brunnen zu pumpen.',
            optionD: 'Die emotionale Belastung von Menschen, die unter Wassermangel leiden.',
            correctOption: 'A',
            category: 'Planetary Health',
            source: 'https://www.unwater.org/water-facts/water-scarcity',
            authorId: adminUser.id,
        },
        {
            text: 'Welche der folgenden Maßnahmen ist ein Beispiel für Klimaanpassung (Adaptation)?',
            optionA: 'Installation von Solaranlagen zur Reduzierung von CO2-Emissionen.',
            optionB: 'Bau von Dämmen und Deichen zum Schutz vor steigendem Meeresspiegel und Überschwemmungen.',
            optionC: 'Umstellung auf Elektromobilität.',
            optionD: 'Aufforstungsprojekte zur Kohlenstoffbindung.',
            correctOption: 'B',
            category: 'Planetary Health',
            source: 'https://www.un.org/en/climatechange/what-is-adaptation',
            authorId: adminUser.id,
        },
        {
            text: 'Wie beeinflusst die Versauerung der Ozeane die Fähigkeit des Meerwassers, CO2 aus der Atmosphäre aufzunehmen?',
            optionA: 'Sie erhöht die Aufnahmekapazität deutlich.',
            optionB: 'Sie hat keinen Einfluss auf die Aufnahmekapazität.',
            optionC: 'Sie kann die Fähigkeit des Ozeans, weiteres CO2 aufzunehmen, verringern.',
            optionD: 'Sie führt dazu, dass der Ozean CO2 schneller wieder an die Atmosphäre abgibt.',
            correctOption: 'C',
            category: 'Planetary Health',
            source: 'https://www.pmel.noaa.gov/co2/story/Ocean+Acidification',
            authorId: adminUser.id,
        },
        {
            text: 'Was ist eine der Hauptfunktionen von städtischen Grünflächen (z.B. Parks, Bäume) im Kontext von Planetary Health?',
            optionA: 'Sie erhöhen den Immobilienwert in der Umgebung.',
            optionB: 'Sie dienen als Lärmschutzbarrieren.',
            optionC: 'Sie können zur Verbesserung der Luftqualität, zur Reduzierung des Hitzeinseleffekts und zur Förderung des Wohlbefindens der Bevölkerung beitragen.',
            optionD: 'Sie sind primär für die landwirtschaftliche Produktion in Städten gedacht.',
            correctOption: 'C',
            category: 'Planetary Health',
            source: 'https://www.who.int/europe/news/item/06-10-2016-urban-green-spaces-a-key-tool-for-improving-health-and-well-being-in-cities',
            authorId: adminUser.id,
        },
        {
            text: 'Welcher Zusammenhang besteht zwischen dem Klimawandel und der globalen Ernährungssicherheit?',
            optionA: 'Der Klimawandel führt weltweit zu höheren Ernteerträgen und verbessert die Ernährungssicherheit.',
            optionB: 'Der Klimawandel hat keinen signifikanten Einfluss auf die Ernährungssicherheit.',
            optionC: 'Der Klimawandel kann durch Extremwetterereignisse, veränderte Niederschlagsmuster und Temperaturanstiege die landwirtschaftliche Produktion bedrohen und die Ernährungssicherheit gefährden.',
            optionD: 'Der Klimawandel beeinflusst nur die Qualität, nicht aber die Quantität der Nahrungsmittelproduktion.',
            correctOption: 'C',
            category: 'Planetary Health',
            source: 'https://www.wfp.org/climate-action',
            authorId: adminUser.id,
        },
        {
            text: 'Was ist das Hauptproblem bei der Verwendung von Einwegplastikprodukten?',
            optionA: 'Sie sind teurer in der Herstellung als Mehrwegalternativen.',
            optionB: 'Sie tragen erheblich zur Umweltverschmutzung bei, insbesondere in den Ozeanen, und zersetzen sich sehr langsam.',
            optionC: 'Sie sind weniger hygienisch als Mehrwegprodukte.',
            optionD: 'Ihre Produktion verbraucht mehr Wasser als die von Mehrwegprodukten.',
            correctOption: 'B',
            category: 'Planetary Health',
            source: 'https://naaee.org/eepro/research/early-childhood',
            authorId: adminUser.id,
        },
    ];

    for (const q of questionsData) {
// ...existing code...
        // Using upsert to avoid duplicate questions if seed is run multiple times
        // It will create if text doesn't exist, or update if it does (though update block is empty here)
        await prisma.question.upsert({
            where: { text: q.text }, // Requires @unique on text field
            update: {
                // Update fields if question already exists, e.g. options or category
                optionA: q.optionA,
                optionB: q.optionB,
                optionC: q.optionC,
                optionD: q.optionD,
                correctOption: q.correctOption,
                category: q.category,
                source: q.source, // Wichtig: Source-Feld auch beim Update aktualisieren
                authorId: q.authorId, // Ensure author is correctly linked
            },
            create: q,
        });
    }
    console.log(`Seeded ${questionsData.length} questions.`);

    console.log('Seeding finished.');
}

main()
    .catch((e) => {
        console.error('Error during seeding:', e);
        process.exit(1);
    })
    .finally(async () => {
        await prisma.$disconnect();
    });